HOME_ROUTE="/"
ABOUT_US_ROUTE="/about"


CONTACT_US_ROUTE="/contact"
CONTACT_ENTRIES_ROUTE="/contact/entries"

ARTICLE_LIST_ROUTE="/articles"

BLOG_POSTS_ROUTE="/blog"
BLOG_POSTS_ADD_ROUTE="/blog/add"

LOGOUT_ROUTE="/logout"
PRICE_ROUTE="/pricing"

CHATBOT_ROUTE="/chat"
# Chat_LIST_ROUTE
# CHAT_LIST_STATE
#CHAT_DETAIL_STATE